### ISSUE TITLE
Talk Proposal - Harnessing the power of the JAMstack with a Headless CMS

### ISSUE THREAD

**Issue by BolajiAyodeji** [jamstack-lagos/meetup#10]
**Title of talk** - Harnessing the power of the JAMstack with a Headless CMS

**Duration of talk** - 30 minutes

**Short description** - Unlike traditional websites that rely heavily on servers, plugins and databases, JAMstack can load JavaScript that receives data from an API and generates markup using a static site generator during deploy time.

Traditional CMS has to be built and hosted together every time it is served and this limits the contents to just the application it is built upon. With headless CMS, the CMS is decoupled and it's data becomes independent and can be served across all platforms via APIs or the Git workflow and on different applications any time whilst maintaining the speed, security, and scalability of the JAMstack.

In this talk, Bolaji will show you how content management can be made easier across all platforms with a Headless CMS.

**Speaker Bio (in third person)**

Bolaji Ayodeji is a [GitHub Campus Expert](https://githubcampus.expert/bolajiayodeji/), Front-end Developer and Technical Writer who currently works in Developer Relations at [Hashnode](https://hashnode.com).

He’s passionate about building JAMstack and PWA applications with a great focus on accessibility and optimization alongside contributing to and supporting FOSS.

Bolaji loves helping tech newbies and junior developers become better at what they do through writing and building inclusive communities.

**What attendees should expect to learn from your talk** - At the end of this talk, attendees should understand: 
- How content management systems work in the JAMstack
- The differences between traditional CMS and the "Headless CMS"
- The categories of Headless CMS (Git based and API driven)
- Several Headless CMS options for their favourite static site generators. 
- Content management best practises

**Specific meetup Date and meetup.com URL** - 14th September 2019 [Meetup Link](https://www.meetup.com/JAMStack-Lagos/events/263995250/)

**Comment by Chuloo** [comment]
Amazing submission. Kindly send in the presentation a week to the event.

**Comment by BolajiAyodeji** [comment]
Alright, I'll do that. 
Thank you for accepting my talk proposal.

**Comment by BolajiAyodeji** [comment]
Here is the link to my slide.
[Click here](https://docs.google.com/presentation/d/19rGyNNWXwHN8IYReQx7PlmDgnGkjabGO2p4kMBamS3E/edit?usp=sharing)
My apologies for submitting it a bit late.

**Comment by lauragift21** [comment]
It's fine @BolajiAyodeji. Slides looks great 💯

We're good to go can't wait to hear your talk!

**Comment by BolajiAyodeji** [comment]
Thank you @lauragift21 
I can't wait too :)
