### ISSUE TITLE
Talk Proposal - Understanding JAMstack with REAL use case

### ISSUE THREAD

**Issue by Oluwasetemi** [jamstack-lagos/meetup#2]
**Title of talk** - Understanding JAMstack with REAL use case

**Duration of talk** - *30* minutes	

**Short description** - Understanding the real use of JAMstack with two major case study of freecodecamp architecture and the Gatsby swags store will show how JAMstack could make life easier for a lot of Nigerian company especially companies with large overhead from huge technology stack that does little or less. It will show developers how to leverage on this new convention in building rich websites with all the modern feel like offline first, progressive apps, low latency support and rich SEO optimizations that are scalable with less or little. The talk will explain some factors to consider when a company or team should adopt JAMstack.

**Speaker Bio (in third person)** - He works as a software developer for [Natterbase](https://natterbase.com), a startup that is working on a software management tool. He loves JavaScript. He is keen on a helping people get in to coding with his love for teaching and learning. He cools off with reading and talking about politics and football. A member of the freecodecamp community in Ibadan.

**What attendees should expect to learn from your talk** - Understanding how to use static sites generators to create new powerful apps that will change the future by understanding the approach others have used via the case study.

**Specific meetup Date and meetup.com URL** - 4th May, 2019 [Meetup link](https://www.meetup.com/JAMStack-Lagos/events/260367214/)

**Comment by Chuloo** [comment]
Hi, @Oluwasetemi thanks for sending in this talk proposal. It's been accepted, kindly send in your slides about a week to the event for reviews. Cheers.

**Comment by Oluwasetemi** [comment]
@Chuloo @lauragift21 thank you very much. My slide will be ready by 27th April 2019. I appreciate the opportunity.

**Comment by Oluwasetemi** [comment]
This is the first rough draft of the [slide](https://jamstacklagosmeetup.netlify.com/). 

the [github link ](https://github.com/Oluwasetemi/jamstack-meetup)

**Comment by Chuloo** [comment]
@Oluwasetemi this is great! Can you verify the dimensions of the slides? Some of the pages seem to over slightly out of view. Thanks.

**Comment by Oluwasetemi** [comment]
@Chuloo @lauragift21 here is the final slide [understand jamstack with use-case](https://understand-jamstack.netlify.com/)
