### ISSUE TITLE
Talk Proposal - The ABC's of Building Fast Sites with Gridsome

### ISSUE THREAD

**Issue by lauragift21** [jamstack-lagos/meetup#3]
**Title of talk:**  The ABC's of Building Fast Sites with Gridsome
**Duration of talk:** 30 minutes
**Short description:** In this talk, I'll give an introduction to Gridsome, A static site generator with Vue.js. How we can leverage the JAMstack in building awesome websites with Gridsome also gives the audience a view on what they can achieve with Gridsome.
**Speaker Bio:** Gift Egwuenu is a Full Stack Developer currently working at Andela, She is passionate about making the web accessible to everyone and also an advocate for building open-source projects and she enjoys solving complex problems using web technologies.
**What attendees should expect to learn from your talk:** By the end of this talk, Attendees will understand how to build a website using Gridsome, and all the possibilities they can leverage by using JAMstack technology in building blazing fast websites.
**Specific meetup Date and meetup.com URL:** 4th May 2019 [Meetup link](https://www.meetup.com/JAMStack-Lagos/events/260367214/)

**Comment by Chuloo** [comment]
Fantastic! Please share a copy of your slides no later than a week before the meetup for reviews. 👍
