### ISSUE TITLE
Talk Proposal - Accessible JAMstack Applications for Everyone

### ISSUE THREAD

**Issue by kenny-io** [jamstack-lagos/meetup#4]
Have you ever had an issue with your mouse and tried to navigate a web page with your keyboard but could not access certain interactive parts? Or perhaps you have listened to the sad tales of a visually impaired person who encounter difficulties while accessing certain websites. 

These are experiences that may leave you wondering how inconsiderate the developer must have been. The web should not discriminate; everybody should be treated equally and given equal ability to access and use the web.

In this talk, I’ll share more light on web accessibility and show developers how to quickly get started in building more accessible websites for everyone.

**Comment by Oluwasetemi** [comment]
Hey, check the [readme](https://github.com/jamstack-lagos/meetup) for the CFP structure.
Nice talk proposal.
