### ISSUE TITLE
Talk Proposal - Activating More Web Functionalities With Puppeteer

### ISSUE THREAD

**Issue by horlah** [jamstack-lagos/meetup#5]
**Title of talk:** Activating More Web Functionalities With Puppeteer
**Duration of talk:** 30 minutes
**Short description:** In this talk, I'd introduce the audience to Puppeteer, Puppeteer is a Node library which provides a high-level API to control Chrome or Chromium over the DevTools Protocol. I'd discuss how Puppeteer can be used to enable more functionalities on the web like Server Side Rendering, converting web pages to PDF and images, e2e tests, Web Scraping e.t.c.
**Speaker Bio:** Emmanuel is a Frontend Developer, currently building [InvestNow](https://apps.apple.com/us/app/investnow/id1474574976?ls=1) for United Capital Plc. Emmanuel has vast experience in building web and hybrid app platforms and has worked with various technology companies in different sectors including healthcare, crypto exchange, transport and finance. He is very passionate about building usable products and loves reflecting his love for art in building those usable products.
**What attendees should expect to learn from your talk:** By the end of this talk, Attendees will understand what Puppeteer really is and learn how to take advantage of it in enabling more functionalities in building JAMstack products.
**Specific meetup Date and meetup.com URL:** 14th September 2019 [Meetup link](https://www.meetup.com/JAMStack-Lagos/events/263995250/)

**Comment by lauragift21** [comment]
Hi @horlah ,

Thanks for sending in a proposal for the JAMstack meetup. We had limited slots for this edition but will like to move your talk to a future  if you're fine with it.

**Comment by horlah** [comment]
Alright, thanks so much. Looking forward to the future meetup. @lauragift21
