### ISSUE TITLE
Talk Proposal - The power of JAMstack: JavaScript • APIs • Markup

### ISSUE THREAD

**Issue by Developerayo** [jamstack-lagos/meetup#6]
**Title of talk:** The power of JAMstack: JavaScript • Markup • APIs

**Duration of talk:** 30 minutes

**Short description:** JAMstack is changing the way we perceive workflow by providing an easier developer experience, far better performance, lower cost, and greater scalability of your application. This talk would give you a dive through the Workflow of JAMstack applications to build time, Static site generation and Headless CMS. 

**Speaker Bio (in the third person):** Shodipo Ayomide is Developer Advocate and Software Engineer, community evangelist organizing @unstackofficial @FBDevCLagos @react-summit. open-source contributor and Native Developer :fire: :rocket:

**What attendees should expect to learn from your talk:** During this talk, you should be able to understand and capture the reason you should adopt cloudinary in whatever product you are building based on the speed, great workflow, scalability, Performance and more.

**Specific meetup Date and meetup.com URL:** **Date:** Saturday, September 14, 2019. **URL:** https://www.meetup.com/JAMStack-Lagos/events/263995250/

**Comment by lauragift21** [comment]
Hi @Developerayo ,

Thanks for sending in a proposal for the JAMstack meetup. We had limited slots for this edition but will like to move your talk to a future  if you're fine with it.

**Comment by Developerayo** [comment]
All Good! 🎉
