### ISSUE TITLE
Talk Proposal - Modern Application Development; Demystifying JAMstack.

### ISSUE THREAD

**Issue by iamuchejude** [jamstack-lagos/meetup#7]
**Title of the talk**
Modern Application Development & Demystifying JAMstack.

**Duration of Talk**
30 minutes

**Short Description**
In this talk, I will be talking about the web and how its process of development has evolved over the years from the incision until the present in terms of performance and usage. I will also be talking about JAMstack which is an approach to modern web development, its benefits and how to get started with it.

**Speaker Bio**
Uche Jude is a Software Engineer, currently working on the on web applications as a freelance software developer. He is very keen on open source and enjoys working on web projects that require conceptual and analytical skills with JavaScript and its related technologies.

**What attendees should expect to learn from your talk**
At the end of this talk, attendees are expected to have an understanding of modern application development and how JAMstack can be used to build modern web applications. 

**Specific meetup Date and meetup.com URL**
Saturday, September 14th, 2019.
[Meetup link](https://www.meetup.com/JAMStack-Lagos/events/263995250/)

**Comment by lauragift21** [comment]
Hi @iamuchejude,

Thanks for sending in a proposal for the JAMstack meetup. We had limited slots for this edition but will like to move your talk to a future if you're fine with it.

**Comment by iamuchejude** [comment]
Sure, I would love to have the talk in a future meetup.
Thanks for your reply.
