### ISSUE TITLE
Talk Proposal - Breaking Down Best Practices for JAMstack

### ISSUE THREAD

**Issue by jemimaabu** [jamstack-lagos/meetup#8]
**Title of talk:** Breaking Down Best Practices for JAMstack

**Duration of talk:** 45 minutes

**Short description:** This talk aims to address the six major best practice guidelines associated with JAMStack and provide detailed explanations, examples and use cases for each.

**Speaker Bio (in the third person):** Jemima Abu is a Front End Developer with over three years experience building accessible and responsive websites, and an avid advocate for diversity and intersectionality in technology.
She's also a huge nerd, slightly obsessed with cats and can usually be found on her laptop, coding or watching slice-of-life anime.

**What attendees should expect to learn from your talk:** 
- How to setup a Content Delivery System on a JAMstack application and examples of CDN services
- Linking preferred version control application to the deployment platform
- Examples of the most up-to-date tools to use for their application
- Setting up build automation based on updates to the code repository
- How to invalidate cached versions of the application 

**Specific meetup Date and meetup.com URL:** 
Saturday, September 14, 2019.
https://www.meetup.com/JAMStack-Lagos/events/263995250/

**Comment by Chuloo** [comment]
Hi @jemimaabu, great talk proposal here. We think the talk is product-centric and focuses a lot on Netlify and its features. Can you re-send a proposal with a more general construct? Looking forward to it.

**Comment by jemimaabu** [comment]
Hey @Chuloo I've updated the proposal.

**Comment by lauragift21** [comment]
Hi @jemimaabu. Thank you! Kindly send in the presentation deck a week to the event.
