### ISSUE TITLE
Talk Proposal - Using multiple Javascript threads to enhance your application

### ISSUE THREAD

**Issue by chiefoleka** [jamstack-lagos/meetup#9]
**Title of talk:** Using multiple Javascript threads to enhance your application

**Duration of talk:** 30 minutes

**Short description:** This talk will explore multi-threading in Javascript and how it can improve application load time, especially in less powerful devices or poor internet connection.

**Speaker Bio:** Valentine Oleka is a software developer at [Time Doctor](https://timedoctor.com). His days have him making improvements to the Time Doctor product to help global companies better manage their remote teams.
Valentine has a strong interest in technology and business, teaching people how to find their way in tech. He has mentored and facilitated several coding boot camps over the last 3 years for Andela, Hotels.ng and Findworka.
On a good day, you will catch Valentine trying so hard to make sure his red cap fits very well before he leaves the house. He has to live up to the "Chief Oleka" name.

**What attendees should expect to learn from my talk:**
- How threading works in Javascript
- Why and how to offload the main thread and use worker threads for processing
- Practical cases to take advantage of threads and workers
- Accessibility and inclusivity gains, thanks to threads and workers
- JAMStack frameworks with support for threads and workers

**Specific meetup Date and meetup.com URL:**
Saturday, September 14, 2019.
https://www.meetup.com/JAMStack-Lagos/events/263995250/

**Comment by lauragift21** [comment]
Hi @chiefoleka 

Thanks for sending in a proposal for the JAMstack meetup. We had limited slots for this edition but will like to move your talk to a future meetup if you're fine with it.

**Comment by chiefoleka** [comment]
Hey,

That's fine by me.
